# Generated by Django 4.1.5 on 2023-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField(max_length=20)),
                ('c_name', models.CharField(max_length=250)),
                ('code', models.IntegerField(max_length=20)),
            ],
        ),
    ]
