# Generated by Django 4.1.5 on 2023-01-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='college',
            name='code',
        ),
    ]
