# Generated by Django 4.1.5 on 2023-01-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_remove_student_s_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='s_id',
            field=models.IntegerField(default=20),
        ),
    ]
